### ISSUE TITLE
first curve can't be set

### ISSUE THREAD

**Issue by telephon** [JVanBuskirk/EnvEdit#1]
Somehow alt-click on the first segment doesn't allow you to edit the first curve.

**Comment by JVanBuskirk** [comment]
It works for me  on OSX.  Select the first node.  Then alt-click while dragging up and down.  It would be nice if you didn't need to select the node first, I'll work on it.

**Comment by telephon** [comment]
ah good. Probably it would be the best to check which node is closest to the click and then use that one.
